apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rv5nx5v0g-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rv5nx5v0g-go 
  name: rv5nx5v0g-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rv5nx5v0g-go 
